"""Foreign Key

Revision ID: 76b46d3e7913
Revises: 7b3651ae27cc
Create Date: 2023-06-14 11:15:36.332801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b46d3e7913'
down_revision = '7b3651ae27cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', sa.String(), nullable=False))
    op.add_column('usuario', sa.Column('usuario_login_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'usuario', ['usuario_login_id'])
    op.drop_constraint('usuario_login_id_fkey', 'usuario', type_='foreignkey')
    op.create_foreign_key(None, 'usuario', 'usuario_login', ['usuario_login_id'], ['id'])
    op.drop_column('usuario', 'login_id')
    op.drop_column('usuario_login', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_login', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuario', sa.Column('login_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.create_foreign_key('usuario_login_id_fkey', 'usuario', 'usuario_login', ['login_id'], ['id'])
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'usuario_login_id')
    op.drop_column('usuario', 'email')
    # ### end Alembic commands ###
