"""Sync

Revision ID: 932e82eedf60
Revises: 7b3651ae27cc
Create Date: 2023-06-23 09:30:19.598324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932e82eedf60'
down_revision = '7b3651ae27cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id_login', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_login')
    )
    op.create_table('usuario')
    op.add_column('usuario', sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('usuario', sa.Column('id_credencial', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('apelido', sa.String(length=30), nullable=True))
    op.add_column('usuario', sa.Column('data_nasc', sa.Date(), nullable=True))
    op.add_column('usuario', sa.Column('data_criacao', sa.Date(), nullable=True))
    op.add_column('usuario', sa.Column('nome_completo', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'usuario', 'login', ['id_credencial'], ['id_login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('usuario_login_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuario', sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('usuario', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.create_foreign_key('usuario_usuario_login_id_fkey', 'usuario', 'usuario_login', ['usuario_login_id'], ['id'])
    op.create_unique_constraint('usuario_usuario_login_id_key', 'usuario', ['usuario_login_id'])
    op.alter_column('usuario', 'nome_completo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('usuario', 'data_criacao')
    op.drop_column('usuario', 'data_nasc')
    op.drop_column('usuario', 'apelido')
    op.drop_column('usuario', 'id_credencial')
    op.drop_column('usuario', 'id_usuario')
    op.create_table('usuario_login',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuario_login_pkey')
    )
    op.drop_table('login')
    # ### end Alembic commands ###
